---
output:
  pdf_document: default
  html_document: default
---
```{r Packages, include=TRUE} 
library("tidyverse")
library("dplyr")
```


```{r reading_data, include=TRUE}
df <- read.csv(file="1_Data/aiddata-countries-only.csv")
df_tidy <- df%>% 
  group_by(year,donor) %>% 
  summarise(total = sum(commitment_amount_usd_constant))%>% 
  mutate(rank = rank(-total))%>% 
  filter(rank<11) %>% 
  rename(c('country_name'='donor')) %>% 
  mutate(Value_rel = total/total[rank==1],Value_lbl=round(total/1e6,2)) %>% 
  rename(c('value'='total')) %>% 
  ungroup()


```
#cite https://towardsdatascience.com/create-animated-bar-charts-using-r-31d09e5841da
```{r}
staticplot = df_tidy %>% 
  ggplot( aes(rank, group = country_name, 
                fill = as.factor(country_name), color = as.factor(country_name))) +
  geom_tile(aes(y = value/2,
                height = value,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(country_name, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=value,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
         axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey" ),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="grey"),
        plot.caption =element_text(size=8, hjust=0.5, face="italic", color="grey"),
        plot.background=element_blank(),
       plot.margin = margin(2,2, 2, 4, "cm"))

anim = staticplot + transition_states(year, transition_length = 4, state_length = 1) +
  view_follow(fixed_x = TRUE)  +
  labs(title = 'GDP per Year : {closest_state}',  
       subtitle  =  "Top 10 Countries",
       caption  = "GDP in Billions USD | Data Source: World Bank Data")
animate(anim, 200, fps = 20,  width = 1200, height = 1000, end_pause = 10, start_pause = 10,
        renderer = gifski_renderer("gganim.gif"))
```


